SET GLOBAL EVENT_SCHEDULER=ON;

USE kodilla_course;

CREATE TABLE STATS (
STAT_ID   INT(11) NOT NULL AUTO_INCREMENT,
STAT_DATE DATETIME NOT NULL,
STAT      VARCHAR(20) NOT NULL,
VALUE     INT(11) NOT NULL,
PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS BESTSELLERS
FROM BOOKS
WHERE BESTSELLER = TRUE;

DELIMITER $$
CREATE EVENT UPDATEBESTSELLERS_COUNT
ON SCHEDULE EVERY 1 minute
  DO
		BEGIN
        DECLARE val INT(11);
        SELECT * INTO val FROM BESTSELLERS_COUNT;
		    CALL UpdateVipLevels();
		    INSERT INTO STATS(STAT_DATE, STAT, VALUE)
			      VALUES(NOW(), 'BESTSELLERS', val);
		    COMMIT;
		END $$
DELIMITER ;